### ISSUE TITLE
Divide refactor work

### ISSUE THREAD

**Issue by slarse** [slarse/Python#2]
Each team member should be given a roughly equally challenging part to refactor into tests. Print statements are probably the hardest to refactor into tests.

Each directory should have precisely one assignee, one issue per directory (subdirs are also dirs!).

**Comment by larshum** [comment]
I did a simple count of the number of places where I could find viable testing data. For example, a print statement was only counted if it used a constant value. I also weighted them based on how complicated I thought they would be to implement. Based on my results, I suggest the following division of directories:
1. `sorts` @slarse 
2. `Maths`, `maths`, `dynamic_programming` @rouwaydhanna 
3. `data_structures/*`, `strings` @mudaliarkartik 
4. `Graph`, `graphs`, `other`, `arithmetic_analysis` @larshum 
5. `ciphers`, `searches` @martinnilsson93 

These are the ones that I think will require the most amount of work. I also found potential test cases in the following directories, but I think they should be divided among us based on who has time left:
* `analysis/compression_analysis` @martinnilsson93 
* `binary_tree` @larshum
* ~~`boolean_algebra`~~ has nothing testable
* `hashes` @larshum
* ~~`machine_learning`~~ has nothing testable
* `matrix` @rouwaydhanna 
* `networking_flow` @rouwaydhanna 

The remaining directories contained no tests or anything that could be converted to a test that I was able to find.

**Comment by mnil2** [comment]
`boolean_algebra` contains only one module, `quine_mc_cluskey`, and AFICT it is not reasonably tested. I think we skip that one too.
