### ISSUE TITLE
List of modules with high amounts of global state

### ISSUE THREAD

**Issue by slarse** [slarse/Python#4]
Some modules have a lot of global state, which would converting their tests a bit... difficult.

* `graphs/multi_hueristic_astar.py`

**Comment by mnil2** [comment]
In the first half:
- `file_transfer_protocol/ftp_client_server.py`
- `file_transfer_protocol/ftp_send_receive.py`
- `graphs/a_star.py`
- `graphs/basic_graphs.py`

Also, some honorary mentions:
- `minimum_spanning_tree_kruskal` and `scc_kosaraju` in `graphs` may look pretty global, but essentially each just contains a top-level pseudo main function.
- Careful with `data_structures/graph/even_tree.py`. The `dfs` function assumes enclosing variables.

**Comment by rouwaydhanna** [comment]
In the second half:
* `hashes.chaos_machine.py` uses `global` keyword to access global variables.
* `machine_learning/gradient_descent.py`
* `machine_learning/Random Forest Classification/random_forest_classification.py`  and `machine_learning/Random Forest Regression/random_forest_regression.py` are basically scripts, no functions
* `other/anagrams.py` also reads from file `other/words`
* `other/detecting_english_programmatically.py` reads from file `other/Dictionary.txt`
* `other/frequency_finder.py`
* `other/password_generator.py` unfinished script
* `other/sierpinski_triangle.py` script
* `searches/ternary_search.py` one global variable

The following functions contained top level code (probably for testing) that should be put into a main function:
* `maths/sieve_of_eratosthenes.py`
* `networking_flow/ford_fulkerson.py`
* `networking_flow/minimum_cut.py`
* `machine_learning/perceptron.py`
* `neural_network/perceptron.py`
* `searches/jump_search.py`
* `simple_client`
* `sorts/BitonicSort.py`
* `sorts/cyclesort.py`
* `sorts/pancake_sort.py`
* `sorts/random_normal_distribution_quicksort.py`
* `sorts/topological_sort.py`
* `sorts/tree_sort.py`

Honorable mentions:
* `machine_learning/k_means_clust.py`, declares unused global variable `TAG`

**Comment by mnil2** [comment]
The test migration #46 is done
